<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UD799V0" failures="1" tests="2" name="ErrorValidationTest" time="23.78" errors="0" timestamp="2023-04-16T12:04:39 BST">
  <testcase classname="rahulshettyacademy.tests.ErrorValidation" name="LoginErrorValidation" time="1.149"/>
  <testcase classname="rahulshettyacademy.tests.ErrorValidation" name="ProductErrorValidation" time="14.333">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rahulshettyacademy.tests.ErrorValidation.ProductErrorValidation(ErrorValidation.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- ErrorValidationTest -->
